//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.23 at 07:46:38 PM CST 
//


package com.fb.goldencudgel.auditDecisionSystem.schema.common;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.namespaces.tns._1545469477904 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ServiceMessage_QNAME = new QName("http://www.example.com/namespaces/tns/1545469477904", "ServiceMessage");
    private final static QName _Message_QNAME = new QName("http://www.example.com/namespaces/tns/1545469477904", "message");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.namespaces.tns._1545469477904
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ServiceMessage }
     * 
     */
    public ServiceMessage createServiceMessage() {
        return new ServiceMessage();
    }

    /**
     * Create an instance of {@link ServiceHeader }
     * 
     */
    public ServiceHeader createServiceHeader() {
        return new ServiceHeader();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link ServiceExtra }
     * 
     */
    public ServiceExtra createServiceExtra() {
        return new ServiceExtra();
    }

    /**
     * Create an instance of {@link ServiceBody }
     * 
     */
    public ServiceBody createServiceBody() {
        return new ServiceBody();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.com/namespaces/tns/1545469477904", name = "ServiceMessage")
    public JAXBElement<ServiceMessage> createServiceMessage(ServiceMessage value) {
        return new JAXBElement<ServiceMessage>(_ServiceMessage_QNAME, ServiceMessage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.com/namespaces/tns/1545469477904", name = "message")
    public JAXBElement<String> createMessage(String value) {
        return new JAXBElement<String>(_Message_QNAME, String.class, null, value);
    }

}
