//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.23 at 07:46:38 PM CST 
//


package com.fb.goldencudgel.auditDecisionSystem.schema.common;

import com.alibaba.fastjson.annotation.JSONField;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceMessage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ServiceHeader" type="{http://www.example.com/namespaces/tns/1545469477904}ServiceHeader"/>
 *         &lt;element name="ServiceBody" type="{http://www.example.com/namespaces/tns/1545469477904}ServiceBody" minOccurs="0"/>
 *         &lt;element name="ServiceExtra" type="{http://www.example.com/namespaces/tns/1545469477904}ServiceExtra" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceMessage", propOrder = {
    "serviceHeader",
    "serviceBody",
    "serviceExtra"
})
public class ServiceMessage {

    @XmlElement(name = "ServiceHeader", required = true)
    @JSONField(name ="ServiceHeader",ordinal = 1)
    protected ServiceHeader serviceHeader;

    @XmlElement(name = "ServiceBody")
    @JSONField(name = "ServiceBody",ordinal = 10)
    protected ServiceBody serviceBody;

    @XmlElement(name = "ServiceExtra")
    @JSONField(name = "ServiceExtra",ordinal = 11)
    protected ServiceExtra serviceExtra;

    /**
     * Gets the value of the serviceHeader property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceHeader }
     *     
     */
    @JsonIgnore
    public ServiceHeader getServiceHeader() {
        return serviceHeader;
    }

    /**
     * Sets the value of the serviceHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceHeader }
     *     
     */
    public void setServiceHeader(ServiceHeader value) {
        this.serviceHeader = value;
    }

    /**
     * Gets the value of the serviceBody property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceBody }
     *     
     */
    @JsonIgnore
    public ServiceBody getServiceBody() {
        return serviceBody;
    }

    /**
     * Sets the value of the serviceBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceBody }
     *     
     */
    public void setServiceBody(ServiceBody value) {
        this.serviceBody = value;
    }

    /**
     * Gets the value of the serviceExtra property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceExtra }
     *     
     */
    @JsonIgnore
    public ServiceExtra getServiceExtra() {
        return serviceExtra;
    }

    /**
     * Sets the value of the serviceExtra property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceExtra }
     *     
     */
    public void setServiceExtra(ServiceExtra value) {
        this.serviceExtra = value;
    }

}
