//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.18 at 04:22:11 PM CST 
//


package com.fb.goldencudgel.auditDecisionSystem.schema.compress;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.example.compressfile package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CompressFileRq_QNAME = new QName("http://www.example.org/compressFile", "compressFileRq");
    private final static QName _CompressFileRs_QNAME = new QName("http://www.example.org/compressFile", "compressFileRs");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.example.compressfile
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CompressFileRs }
     * 
     */
    public CompressFileRs createCompressFileRs() {
        return new CompressFileRs();
    }

    /**
     * Create an instance of {@link CompressFileRq }
     * 
     */
    public CompressFileRq createCompressFileRq() {
        return new CompressFileRq();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompressFileRq }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/compressFile", name = "compressFileRq")
    public JAXBElement<CompressFileRq> createCompressFileRq(CompressFileRq value) {
        return new JAXBElement<CompressFileRq>(_CompressFileRq_QNAME, CompressFileRq.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompressFileRs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/compressFile", name = "compressFileRs")
    public JAXBElement<CompressFileRs> createCompressFileRs(CompressFileRs value) {
        return new JAXBElement<CompressFileRs>(_CompressFileRs_QNAME, CompressFileRs.class, null, value);
    }

}
